---
title: "Standardization and Decomposition: An Introduction for Social Scientists"
subtitle: "Workshop 15 July 2026"
author: "Ben Matthews & Josiah King"
---

```{r}
#| include: false
file.copy("dgp_preprint.pdf","docs/dgp_preprint.pdf")
file.copy("Das Gupta 1993 - Standardization and Decomposition of Rates.pdf","docs/dg1993_manual.pdf")
dir.create("docs/data")
lapply(list.files("data",full.names=TRUE), \(x) file.copy(x,"docs/data"))
```

# Overview

#### When

Wednesday 15th July 2026  

#### Where

- In-person: University of Stirling, Cottrell Building, 2Y5. [Click here for the map!](https://link.mazemap.com/ioL7EsvH){target="_blank"}  
- Online: The session will be recorded and transcribed via Teams. If you are joining online please use the [link here](https://teams.microsoft.com/meet/330901632633208?p=fPyl1PD2AstUWviDs9){target="_blank"}

#### What to prepare?  

Please bring your own laptop with either R or Stata installed. If you cannot install either R or Stata on your own machine you will be able to complete practical exercises in R via a web browser, but for this you will need a free account with [posit.cloud](https://posit.cloud/){target="_blank"}.  If you would like to use this 
option please sign up for an account at posit.cloud before the session.  


# Schedule

::::{.columns}
:::{.column width="65%"}
__Sessions__  

- [Welcome/Intro](lecture00.html)  
- [Introduction to Standardisation and Decomposition](lecture-conceptual.html)  
- [The whole game](lecture-whole-game.html)  
- [Standardisation & Decomposition of Rates as Products](lecture-stddecompbasics.html)  
- [Practical 1](workshop01.html)  
- [Cross-classified Data & Multiple Populations](lecture-crossclass.html)  
- [Practical 2](workshop02.html)  
- [Uncertainty](lecture-uncertainty.html)  
- [Practical 3](workshop03.html)
- [Close](lecture-close.html)  
<!-- [Other Methods of Decomposition](lecture-othermethods.html) -->

:::
:::{.column width="5%"}
:::
:::{.column width="30%"}
__Breaks__  

<br><br>
11:00-11:15: Coffee  
<br><br>
12:15-13:15: Lunch  
<br><br>
14:15-14:30: Coffee

:::
::::

